### ISSUE TITLE
NotImplementedError: Non-relative patterns are unsupported

### ISSUE THREAD

**Issue by ryanpeach** [ryanpeach/renag#8]
Needs the ability to support single files and only include subdirectories.

**Comment by ryanpeach** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/renag", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/renag/__main__.py", line 165, in main
    all_files |= set(analyze_dir.rglob(g))
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1135, in rglob
    raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
```

**Comment by ryanpeach** [comment]
Didn't make glob a list
