### ISSUE TITLE
Is a directory

### ISSUE THREAD

**Issue by ryanpeach** [ryanpeach/renag#9]
```
Traceback (most recent call last):
  File "/usr/local/bin/renag", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/renag/__main__.py", line 208, in main
    with file2.open("r") as f2:
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
IsADirectoryError: [Errno 21] Is a directory: '/Users/.../Documents/Workspace/.../.git/objects/00'
```

**Comment by ryanpeach** [comment]
```
from pyparsing import Literal
from renag import Complainer, Severity

class AdditionalPropertiesComplainer(Complainer):
    """
    Don't use additionalProperties because it makes it difficult for the golang type system.
    REF: https://github.com/deepmap/oapi-codegen#additional-properties-in-type-definitions
    """
    capture = Literal('additionalProperties')
    severity = Severity.CRITICAL
    glob = '*.yaml'
    exclude = ['.git/**/*']
```

**Comment by ryanpeach** [comment]
Didn't make glob a list

**Comment by ryanpeach** [comment]
Actually this is still a problem if you set `glob = ["*"]`

**Comment by ryanpeach** [comment]
```
renag/__main__.py", line 208, in main
    with file2.open("r") as f2:
  File "/usr/local/Cellar/python@3.7/3.7.13_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
IsADirectoryError: [Errno 21] Is a directory
```

**Comment by ryanpeach** [comment]
https://github.com/ryanpeach/renag/blob/444675a353a9c1728ac3af36715103ae6ccb3dee/renag/__main__.py#L165

Just need to check for is_file here.
